### ISSUE TITLE
stateless mode

### ISSUE THREAD

**Issue by ralphbean** [kushaldas/tunir#1]
It is cool that tunir can keep its own database of its job results.

But if it were to run inside taskotron, taskotron's `resultsdb` service would be responsible for holding those results.

Accordingly, it would be cool if tunir had a `--stateless` mode that would run the test, print the results, and quit without connecting to a database and storing any data.

**Comment by kushaldas** [comment]
Commit d8382b837a178a8bf3557ee7b363afb388080627 adds this feature.
