### ISSUE TITLE
Create /var/run/tunir for vagrant jobs.

### ISSUE THREAD

**Issue by kushaldas** [kushaldas/tunir#18]
Remember to create /var/run/tunir for vagrant based jobs.

**Comment by kushaldas** [comment]
Easiest way to call system('mkdir -p /var/run/tunir') in **init**.py just before starting a vagrant job.

**Comment by farhaanbukhsh** [comment]
Hey @kushaldas , I want to a stab to fix , trying to set up the development environment, any thing specific should I do while setting it up?

**Comment by kushaldas** [comment]
Nope, everything is supposed to be in the docs :)

**Comment by farhaanbukhsh** [comment]
I sent a PR , okay I have a doubt , how do I test the code ?

**Comment by kushaldas** [comment]
Fixed in https://github.com/kushaldas/tunir/commit/96bf70d9f4b69a74ba1d74f7f21ee202c96b9d3f
