### ISSUE TITLE
/docs/installation.rst - apache-libcloud needed

### ISSUE THREAD

**Issue by agajdosi** [kushaldas/tunir#47]
Followed installation guide on Fedora 24 with python 2.7.12. After running `$ tunir -h` it seems tunir is missing libcloud.

> Traceback (most recent call last):
>   File "./tunir", line 5, in <module>
>     from tunirlib import startpoint
>   File "/home/agajdosi/git/tunir/tunirlib/**init**.py", line 6, in <module>
>     from tuniraws import aws_and_run
>   File "/home/agajdosi/git/tunir/tunirlib/tuniraws.py", line 19, in <module>
>     from libcloud.compute.types import Provider

Resolved by installing libcloud: `pip install apache-libcloud`.

**Comment by kushaldas** [comment]
Sorry for missing this ticket, will update the docs accordingly. In case you are using Fedora, it is better that you directly use the packaged Tunir in Fedora.
